export const SCOTIACARDPROFILEINQS: any[] = [
    {
        "transactionStatus": "0",
        "traceUser": "4536055024554601",
        "custContact": [{
            "phone": "(416) 852-6985",
            "city": "TORONTO",
            "addr1": "1987 EGLINTON ROAD",
            "country": "CA",
            "postalCode": "M1M1M1",
            "addr2": "",
            "state": "ON"
        }],
        "cardEntitlementLimits": [{
            "weeklyEntlLimit": "0",
            "dailyEntlLimit": "0",
            "weeklyAvailEntlLimit": "0",
            "dailyAvailEntlLimit": "0"
        }],
        "savedApplicationsList": [],
        "modifiedMsgCenter": [],
        "CustomerSysIDs": "BRK,CI,BANKING,CI-CSS-002134071202675 ,CI-CID-002134071202675,KT-ANT-002134071202675,acxsys-CRP-002134071202675,IP-CID-002134071202675,SKR-SKR-0000000000000124,epost-WDX-002134071202675,AC-CARDTYPE-P,",
        "EXRate": "1.0",
        "bankAcctRec": [],
        "traceLanguage": "en",
        "cardEntitlements": "null, null, TRAVEL_FLAG, null, null, null, PRODAPP_GIC_TARGETED, null, null, null, null, SCOTIA_INVESTMENTS, null, USER_ID, SAVE_AND_COMPLETE, null, null, GLOBAL_COMM_PREFERENCE, null, PRODAPP_MUTUAL_FUND, CHANGE_RECORDKEEPING_DDA, null, RETAIL_ONLY_CARD_TYPE, UNRESTRICTED_CARD_TYPE, PRODAPP_RMT, PRODAPP_INV, ERECEIPTS, PRODAPP_VPA, LOYALTY, PRODAPP_BVP, null, PRODAPP_PAO, SUPP_CARD_SA, null, null, null, null, null, ALERTS, PENDING_TRANSACTIONS, null, null, null, null, INTERAC_E-TRANSFER, null, TRANSFERS, ESTORE, null, EPOST, null, BILL_PAYMENTS, PRODAPP_PAV, null, null, null, null, null, null, null, null, CHANGE_RECORDKEEPING_BORROWING, CREDIT_TRANSACTION_HISTORY, WESTERN_UNION, null, null, null, null, null, STATEMENT_ALERT_MAMAP, STATEMENT_ALERT_MMA, REMOTE_DEPOSIT_CAPTURE,",
        "traceTxId": "bd4fdd88-1200-4d94-8ad7-e568d93189b1",
        "exception": [],
        "savedApplicationsFlag": false,
        "closeAccountList": [{
            "dateOpened": "2015-04-30-04:00",
            "productCode": "SAV",
            "balance_amt": "0.00",
            "ProductSubCode": "BB",
            "accountName": "Basic Banking",
            "classifications": [{
                "REL_ACTIVITY": "RetailDep",
                "detail": "Deposit",
                "default": "Savings",
                "RETAIL_BANKING": "Chequing"
            }],
            "currency": "CAD",
            "ddAccountNum": "018000361720",
            "category": "Banking",
            "STEPIndent": false,
            "balance": "0.00",
            "AccountKind": "CL",
            "segCategory": "Banking",
            "entitlements": "svst",
            "branchLocatorTransit": "01800",
            "id": "************1720",
            "BankAcctStatusCode": "CL",
            "accountKey": "-1053084031",
            "ProductRelationship": "SOL",
            "iTradeAccountKey": "-989177531"
        }, {
            "iTradeAccountKey": "1391772669",
            "productCode": "VCL",
            "balance_amt": "0.00",
            "ProductSubCode": "DM",
            "accountName": "Scotia Momentum VISA Infinite",
            "classifications": [{
                "REL_ACTIVITY": "RetailVisaMomentum",
                "detail": "VisaRebates",
                "default": "Visa",
                "RETAIL_BANKING": " "
            }],
            "currency": "CAD",
            "creditorInsuranceIndicator": " ",
            "ddAccountNum": "4538260008110010",
            "category": "Borrowing",
            "STEPIndent": false,
            "balance": "0.00",
            "AccountKind": "CLS",
            "segCategory": "Borrowing",
            "entitlements": "bast",
            "branchLocatorTransit": "80002",
            "id": "************0010",
            "cardImageAlias": "credit_scotiamomentumvisainfinite",
            "BankAcctStatusCode": "CL",
            "accountKey": "1327866169",
            "ProductRelationship": "SOL",
            "dateOpened": "2011-09-01-04:00"
        }, {
            "iTradeAccountKey": "632991843",
            "productCode": "MOR",
            "balance_amt": "0.00",
            "ProductSubCode": "UN",
            "accountName": "Scotia Mortgage",
            "classifications": [{
                "REL_ACTIVITY": "Mortgage",
                "detail": "Mortgage",
                "default": "Mortgage",
                "RETAIL_BANKING": " "
            }],
            "currency": "CAD",
            "creditorInsuranceIndicator": " ",
            "ddAccountNum": "1000736",
            "category": "Borrowing",
            "STEPIndent": false,
            "balance": "0.00",
            "AccountKind": "CLS",
            "segCategory": "Borrowing",
            "entitlements": "msta",
            "branchLocatorTransit": "40592",
            "id": "************0736",
            "BankAcctStatusCode": "CL",
            "accountKey": "569085343",
            "ProductRelationship": "COS",
            "dateOpened": "2005-08-25-04:00"
        }, {
            "iTradeAccountKey": "633047979",
            "productCode": "MOR",
            "balance_amt": "0.00",
            "ProductSubCode": "DI",
            "accountName": "Scotia Mortgage",
            "classifications": [{
                "REL_ACTIVITY": "Mortgage",
                "detail": "Mortgage",
                "default": "Mortgage",
                "RETAIL_BANKING": " "
            }],
            "currency": "CAD",
            "creditorInsuranceIndicator": " ",
            "ddAccountNum": "1000905",
            "category": "Borrowing",
            "STEPIndent": false,
            "balance": "0.00",
            "AccountKind": "CLS",
            "segCategory": "Borrowing",
            "entitlements": "msta",
            "branchLocatorTransit": "40592",
            "id": "************0905",
            "BankAcctStatusCode": "CL",
            "accountKey": "569141479",
            "ProductRelationship": "COS",
            "dateOpened": "2005-12-02-05:00"
        }, {
            "iTradeAccountKey": "633738447",
            "productCode": "MOR",
            "balance_amt": "0.00",
            "ProductSubCode": "UN",
            "accountName": "Scotia Mortgage",
            "classifications": [{
                "REL_ACTIVITY": "Mortgage",
                "detail": "Mortgage",
                "default": "Mortgage",
                "RETAIL_BANKING": " "
            }],
            "currency": "CAD",
            "creditorInsuranceIndicator": " ",
            "ddAccountNum": "1001153",
            "category": "Borrowing",
            "STEPIndent": false,
            "balance": "0.00",
            "AccountKind": "CLS",
            "segCategory": "Borrowing",
            "entitlements": "msta",
            "branchLocatorTransit": "80077",
            "id": "************1153",
            "BankAcctStatusCode": "CL",
            "accountKey": "569831947",
            "ProductRelationship": "COS",
            "dateOpened": "2006-03-06-05:00"
        }, {
            "iTradeAccountKey": "633772051",
            "productCode": "MOR",
            "balance_amt": "0.00",
            "ProductSubCode": "UN",
            "accountName": "Scotia Mortgage",
            "classifications": [{
                "REL_ACTIVITY": "Mortgage",
                "detail": "Mortgage",
                "default": "Mortgage",
                "RETAIL_BANKING": " "
            }],
            "currency": "CAD",
            "creditorInsuranceIndicator": " ",
            "ddAccountNum": "1001292",
            "category": "Borrowing",
            "STEPIndent": false,
            "balance": "0.00",
            "AccountKind": "CLS",
            "segCategory": "Borrowing",
            "entitlements": "msta",
            "branchLocatorTransit": "40592",
            "id": "************1292",
            "BankAcctStatusCode": "CL",
            "accountKey": "569865551",
            "ProductRelationship": "COS",
            "dateOpened": "2006-02-06-05:00"
        }, {
            "iTradeAccountKey": "640295288",
            "productCode": "MOR",
            "balance_amt": "0.00",
            "ProductSubCode": "UN",
            "accountName": "Scotia Mortgage",
            "classifications": [{
                "REL_ACTIVITY": "Mortgage",
                "detail": "Mortgage",
                "default": "Mortgage",
                "RETAIL_BANKING": " "
            }],
            "currency": "CAD",
            "creditorInsuranceIndicator": " ",
            "ddAccountNum": "1008481",
            "category": "Borrowing",
            "STEPIndent": false,
            "balance": "0.00",
            "AccountKind": "CLS",
            "segCategory": "Borrowing",
            "entitlements": "msta",
            "branchLocatorTransit": "80002",
            "id": "************8481",
            "BankAcctStatusCode": "CL",
            "accountKey": "576388788",
            "ProductRelationship": "COS",
            "dateOpened": "2007-03-09-05:00"
        }, {
            "iTradeAccountKey": "640295319",
            "productCode": "MOR",
            "balance_amt": "0.00",
            "ProductSubCode": "UN",
            "accountName": "Scotia Mortgage",
            "classifications": [{
                "REL_ACTIVITY": "Mortgage",
                "detail": "Mortgage",
                "default": "Mortgage",
                "RETAIL_BANKING": " "
            }],
            "currency": "CAD",
            "creditorInsuranceIndicator": " ",
            "ddAccountNum": "1008482",
            "category": "Borrowing",
            "STEPIndent": false,
            "balance": "0.00",
            "AccountKind": "CLS",
            "segCategory": "Borrowing",
            "entitlements": "msta",
            "branchLocatorTransit": "80002",
            "id": "************8482",
            "BankAcctStatusCode": "CL",
            "accountKey": "576388819",
            "ProductRelationship": "COS",
            "dateOpened": "2007-03-09-05:00"
        }, {
            "iTradeAccountKey": "640296249",
            "productCode": "MOR",
            "balance_amt": "0.00",
            "ProductSubCode": "UN",
            "accountName": "Scotia Mortgage",
            "classifications": [{
                "REL_ACTIVITY": "Mortgage",
                "detail": "Mortgage",
                "default": "Mortgage",
                "RETAIL_BANKING": " "
            }],
            "currency": "CAD",
            "creditorInsuranceIndicator": " ",
            "ddAccountNum": "1008491",
            "category": "Borrowing",
            "STEPIndent": false,
            "balance": "0.00",
            "AccountKind": "CLS",
            "segCategory": "Borrowing",
            "entitlements": "msta",
            "branchLocatorTransit": "80002",
            "id": "************8491",
            "BankAcctStatusCode": "CL",
            "accountKey": "576389749",
            "ProductRelationship": "COS",
            "dateOpened": "2007-03-09-05:00"
        }, {
            "iTradeAccountKey": "640296280",
            "productCode": "MOR",
            "balance_amt": "0.00",
            "ProductSubCode": "UN",
            "accountName": "Scotia Mortgage",
            "classifications": [{
                "REL_ACTIVITY": "Mortgage",
                "detail": "Mortgage",
                "default": "Mortgage",
                "RETAIL_BANKING": " "
            }],
            "currency": "CAD",
            "creditorInsuranceIndicator": " ",
            "ddAccountNum": "1008492",
            "category": "Borrowing",
            "STEPIndent": false,
            "balance": "0.00",
            "AccountKind": "CLS",
            "segCategory": "Borrowing",
            "entitlements": "msta",
            "branchLocatorTransit": "80002",
            "id": "************8492",
            "BankAcctStatusCode": "CL",
            "accountKey": "576389780",
            "ProductRelationship": "COS",
            "dateOpened": "2007-03-09-05:00"
        }, {
            "iTradeAccountKey": "641218809",
            "productCode": "MOR",
            "balance_amt": "0.00",
            "ProductSubCode": "UN",
            "accountName": "Scotia Mortgage",
            "classifications": [{
                "REL_ACTIVITY": "Mortgage",
                "detail": "Mortgage",
                "default": "Mortgage",
                "RETAIL_BANKING": " "
            }],
            "currency": "CAD",
            "creditorInsuranceIndicator": " ",
            "ddAccountNum": "1009481",
            "category": "Borrowing",
            "STEPIndent": false,
            "balance": "0.00",
            "AccountKind": "CLS",
            "segCategory": "Borrowing",
            "entitlements": "msta",
            "branchLocatorTransit": "60012",
            "id": "************9481",
            "BankAcctStatusCode": "CL",
            "accountKey": "577312309",
            "ProductRelationship": "COS",
            "dateOpened": "2002-10-30-05:00"
        }, {
            "iTradeAccountKey": "1708163631",
            "productCode": "SCL",
            "balance_amt": "-18991.04",
            "ProductSubCode": "RL",
            "accountName": "Scotia RSP Catch-Up LOC",
            "classifications": [{
                "REL_ACTIVITY": "RetailRSPLOC",
                "detail": "LineOfCredit",
                "default": "LineOfCredit",
                "RETAIL_BANKING": " "
            }],
            "currency": "CAD",
            "creditorInsuranceIndicator": " ",
            "ddAccountNum": "4538157000014",
            "category": "Borrowing",
            "STEPIndent": false,
            "balance": "-18,991.04",
            "AccountKind": "CLS",
            "segCategory": "Borrowing",
            "entitlements": "bast",
            "branchLocatorTransit": "40592",
            "id": "************0014",
            "BankAcctStatusCode": "CL",
            "accountKey": "1644257131",
            "ProductRelationship": "COS",
            "dateOpened": "2000-01-01-05:00"
        }, {
            "iTradeAccountKey": "1032119773",
            "productCode": "VAX",
            "balance_amt": "-1641.33",
            "ProductSubCode": "SC",
            "accountName": "Scotiabank Amex Card",
            "classifications": [{
                "REL_ACTIVITY": "AmexRewards",
                "detail": "AmexRewards",
                "default": "Amex",
                "RETAIL_BANKING": " "
            }],
            "currency": "CAD",
            "creditorInsuranceIndicator": " ",
            "ddAccountNum": "379240004832015",
            "category": "Borrowing",
            "STEPIndent": false,
            "balance": "-1,641.33",
            "AccountKind": "CLS",
            "segCategory": "Borrowing",
            "entitlements": "bast",
            "branchLocatorTransit": "40592",
            "id": "************2015",
            "cardImageAlias": "credit_scotiaamexstandard",
            "BankAcctStatusCode": "CL",
            "accountKey": "968213273",
            "ProductRelationship": "SOL",
            "dateOpened": "2012-11-01-04:00"
        }, {
            "iTradeAccountKey": "-230554903",
            "productCode": "VAX",
            "balance_amt": "-50102.93",
            "ProductSubCode": "GC",
            "accountName": "Scotiabank Gold Amex Card",
            "classifications": [{
                "REL_ACTIVITY": "AmexRewards",
                "detail": "AmexRewards",
                "default": "Amex",
                "RETAIL_BANKING": " "
            }],
            "currency": "CAD",
            "creditorInsuranceIndicator": " ",
            "ddAccountNum": "379241001029019",
            "category": "Borrowing",
            "STEPIndent": false,
            "balance": "-50,102.93",
            "AccountKind": "CLS",
            "segCategory": "Borrowing",
            "entitlements": "bast",
            "branchLocatorTransit": "80002",
            "id": "************9019",
            "cardImageAlias": "credit_scotiaamexgold",
            "BankAcctStatusCode": "CL",
            "accountKey": "-294461403",
            "ProductRelationship": "SOL",
            "dateOpened": "2011-09-01-04:00"
        }, {
            "productCode": "NRS",
            "usd_balance": "0.00",
            "ProductSubCode": "",
            "cad_balance": "0.00",
            "accountName": "Non-Reg Savings - BNS",
            "classifications": [{
                "REL_ACTIVITY": "RetailNonRegBNS",
                "detail": "IP",
                "default": "BNS",
                "RETAIL_BANKING": " "
            }],
            "usd_balance_amt": "0",
            "ddAccountNum": "000000000680631",
            "category": "Investing",
            "STEPIndent": false,
            "AccountKind": "CLS",
            "branchLocatorTransit": "80002",
            "segCategory": "Investing",
            "cad_balance_amt": "0",
            "entitlements": "isoc",
            "id": "************0631",
            "BankAcctStatusCode": "CL",
            "accountKey": "847585707",
            "ProductRelationship": "SOL",
            "iTradeAccountKey": "911492207"
        }, {
            "productCode": "NRS",
            "usd_balance": "0.00",
            "ProductSubCode": "",
            "cad_balance": "0.00",
            "accountName": "Non-Reg Savings - BNS",
            "classifications": [{
                "REL_ACTIVITY": "RetailNonRegBNS",
                "detail": "IP",
                "default": "BNS",
                "RETAIL_BANKING": " "
            }],
            "usd_balance_amt": "0",
            "ddAccountNum": "000000000680686",
            "category": "Investing",
            "STEPIndent": false,
            "AccountKind": "CLS",
            "branchLocatorTransit": "80002",
            "segCategory": "Investing",
            "cad_balance_amt": "0",
            "entitlements": "isoc",
            "id": "************0686",
            "BankAcctStatusCode": "CL",
            "accountKey": "847590667",
            "ProductRelationship": "SOL",
            "iTradeAccountKey": "911497167"
        }, {
            "productCode": "NRS",
            "usd_balance": "0.00",
            "ProductSubCode": "",
            "cad_balance": "0.00",
            "accountName": "Non-Reg Savings - BNS",
            "classifications": [{
                "REL_ACTIVITY": "RetailNonRegBNS",
                "detail": "IP",
                "default": "BNS",
                "RETAIL_BANKING": " "
            }],
            "usd_balance_amt": "0",
            "ddAccountNum": "000000000680695",
            "category": "Investing",
            "STEPIndent": false,
            "AccountKind": "CLS",
            "branchLocatorTransit": "80002",
            "segCategory": "Investing",
            "cad_balance_amt": "0",
            "entitlements": "isoc",
            "id": "************0695",
            "BankAcctStatusCode": "CL",
            "accountKey": "847591597",
            "ProductRelationship": "SOL",
            "iTradeAccountKey": "911498097"
        }, {
            "productCode": "NRS",
            "usd_balance": "0.00",
            "ProductSubCode": "",
            "cad_balance": "0.00",
            "accountName": "Non-Reg Savings - BNS",
            "classifications": [{
                "REL_ACTIVITY": "RetailNonRegBNS",
                "detail": "IP",
                "default": "BNS",
                "RETAIL_BANKING": " "
            }],
            "usd_balance_amt": "0",
            "ddAccountNum": "000000000686092",
            "category": "Investing",
            "STEPIndent": false,
            "AccountKind": "CLS",
            "branchLocatorTransit": "80002",
            "segCategory": "Investing",
            "cad_balance_amt": "0",
            "entitlements": "isoc",
            "id": "************6092",
            "BankAcctStatusCode": "CL",
            "accountKey": "852953884",
            "ProductRelationship": "SOL",
            "iTradeAccountKey": "916860384"
        }, {
            "productCode": "RRS",
            "usd_balance": "0.00",
            "ProductSubCode": "SB",
            "cad_balance": "0.00",
            "accountName": "Registered Savings - BNS",
            "classifications": [{
                "REL_ACTIVITY": "RetailRegBNS",
                "detail": "IP",
                "default": "BNS",
                "RETAIL_BANKING": " "
            }],
            "usd_balance_amt": "0",
            "ddAccountNum": "000000000680640",
            "category": "Investing",
            "STEPIndent": false,
            "AccountKind": "CLS",
            "branchLocatorTransit": "80002",
            "segCategory": "Investing",
            "cad_balance_amt": "0",
            "entitlements": "isoc",
            "id": "************0640",
            "BankAcctStatusCode": "CL",
            "accountKey": "847586637",
            "ProductRelationship": "SOL",
            "iTradeAccountKey": "911495776"
        }, {
            "productCode": "RRS",
            "usd_balance": "0.00",
            "ProductSubCode": "SB",
            "cad_balance": "0.00",
            "accountName": "Registered Savings - BNS",
            "classifications": [{
                "REL_ACTIVITY": "RetailRegBNS",
                "detail": "IP",
                "default": "BNS",
                "RETAIL_BANKING": " "
            }],
            "usd_balance_amt": "0",
            "ddAccountNum": "000000000680668",
            "category": "Investing",
            "STEPIndent": false,
            "AccountKind": "CLS",
            "branchLocatorTransit": "80002",
            "segCategory": "Investing",
            "cad_balance_amt": "0",
            "entitlements": "isoc",
            "id": "************0668",
            "BankAcctStatusCode": "CL",
            "accountKey": "847588807",
            "ProductRelationship": "SOL",
            "iTradeAccountKey": "911497946"
        }, {
            "productCode": "RRS",
            "usd_balance": "0.00",
            "ProductSubCode": "SB",
            "cad_balance": "0.00",
            "accountName": "Registered Savings - BNS",
            "classifications": [{
                "REL_ACTIVITY": "RetailRegBNS",
                "detail": "IP",
                "default": "BNS",
                "RETAIL_BANKING": " "
            }],
            "usd_balance_amt": "0",
            "ddAccountNum": "000000000680677",
            "category": "Investing",
            "STEPIndent": false,
            "AccountKind": "CLS",
            "branchLocatorTransit": "80002",
            "segCategory": "Investing",
            "cad_balance_amt": "0",
            "entitlements": "isoc",
            "id": "************0677",
            "BankAcctStatusCode": "CL",
            "accountKey": "847589737",
            "ProductRelationship": "SOL",
            "iTradeAccountKey": "911498876"
        }, {
            "productCode": "RRS",
            "usd_balance": "0.00",
            "ProductSubCode": "",
            "cad_balance": "0.00",
            "accountName": "Registered Savings - SSI",
            "classifications": [{
                "REL_ACTIVITY": "RetailRegSSI",
                "detail": "IP",
                "default": "SSI",
                "RETAIL_BANKING": " "
            }],
            "usd_balance_amt": "0",
            "ddAccountNum": "000000000425622",
            "category": "Investing",
            "STEPIndent": false,
            "AccountKind": "CLS",
            "branchLocatorTransit": "80002",
            "segCategory": "Investing",
            "cad_balance_amt": "0",
            "entitlements": "isoc",
            "id": "************5622",
            "BankAcctStatusCode": "CL",
            "accountKey": "-1094579886",
            "ProductRelationship": "SOL",
            "iTradeAccountKey": "-1030673386"
        }, {
            "productCode": "RRS",
            "usd_balance": "0.00",
            "ProductSubCode": "",
            "cad_balance": "0.00",
            "accountName": "Registered Savings - SSI",
            "classifications": [{
                "REL_ACTIVITY": "RetailRegSSI",
                "detail": "IP",
                "default": "SSI",
                "RETAIL_BANKING": " "
            }],
            "usd_balance_amt": "0",
            "ddAccountNum": "000000000425668",
            "category": "Investing",
            "STEPIndent": false,
            "AccountKind": "CLS",
            "branchLocatorTransit": "80002",
            "segCategory": "Investing",
            "cad_balance_amt": "0",
            "entitlements": "isoc",
            "id": "************5668",
            "BankAcctStatusCode": "CL",
            "accountKey": "-1094575856",
            "ProductRelationship": "SOL",
            "iTradeAccountKey": "-1030669356"
        }, {
            "productCode": "TFS",
            "usd_balance": "0.00",
            "ProductSubCode": "SB",
            "cad_balance": "0.00",
            "accountName": "Tax-Free Savings - BNS",
            "classifications": [{
                "REL_ACTIVITY": "TFSABNS",
                "detail": "IP",
                "default": "BNS",
                "RETAIL_BANKING": " "
            }],
            "usd_balance_amt": "0",
            "ddAccountNum": "000000000432981",
            "category": "Investing",
            "STEPIndent": false,
            "AccountKind": "CLS",
            "branchLocatorTransit": "80002",
            "segCategory": "Investing",
            "cad_balance_amt": "0",
            "entitlements": "isoc",
            "id": "************2981",
            "BankAcctStatusCode": "CL",
            "accountKey": "-1068626190",
            "ProductRelationship": "SOL",
            "iTradeAccountKey": "-1004717051"
        }, {
            "productCode": "TFS",
            "usd_balance": "0.00",
            "ProductSubCode": "SB",
            "cad_balance": "0.00",
            "accountName": "Tax-Free Savings - BNS",
            "classifications": [{
                "REL_ACTIVITY": "TFSABNS",
                "detail": "IP",
                "default": "BNS",
                "RETAIL_BANKING": " "
            }],
            "usd_balance_amt": "0",
            "ddAccountNum": "000000000435728",
            "category": "Investing",
            "STEPIndent": false,
            "AccountKind": "CLS",
            "branchLocatorTransit": "80002",
            "segCategory": "Investing",
            "cad_balance_amt": "0",
            "entitlements": "isoc",
            "id": "************5728",
            "BankAcctStatusCode": "CL",
            "accountKey": "-1065920758",
            "ProductRelationship": "SOL",
            "iTradeAccountKey": "-1002011619"
        }],
        "accountList": [{
            "dateOpened": "2015-03-31-04:00",
            "productCode": "SAV",
            "balance_amt": "25324.53",
            "ProductSubCode": "BB",
            "accountName": "Basic Banking",
            "classifications": [{
                "REL_ACTIVITY": "RetailDep",
                "detail": "Deposit",
                "default": "Savings",
                "RETAIL_BANKING": "Chequing"
            }],
            "currency": "CAD",
            "ddAccountNum": "405922310023",
            "category": "Banking",
            "STEPIndent": false,
            "balance": "25,324.53",
            "AccountKind": "FZN",
            "segCategory": "Banking",
            "entitlements": "crco,dddd,adet,view,hpas,svst,ahis",
            "branchLocatorTransit": "40592",
            "id": "************0023",
            "BankAcctStatusCode": "OP",
            "accountKey": "992887778",
            "ProductRelationship": "SOL",
            "iTradeAccountKey": "1056794278"
        }, {
            "dateOpened": "2015-06-03-04:00",
            "productCode": "SAV",
            "balance_amt": "0.00",
            "ProductSubCode": "MS",
            "accountName": "Momentum Savings",
            "classifications": [{
                "REL_ACTIVITY": "HighInterestBonus",
                "detail": "HighInterestBonus",
                "default": "Savings",
                "RETAIL_BANKING": "Saving"
            }],
            "currency": "CAD",
            "ddAccountNum": "405920414484",
            "category": "Banking",
            "STEPIndent": false,
            "balance": "0.00",
            "AccountKind": "FZN",
            "segCategory": "Banking",
            "entitlements": "dddd,adet,view,hpas,crin,svst,ahis",
            "branchLocatorTransit": "40592",
            "id": "************4484",
            "BankAcctStatusCode": "OP",
            "accountKey": "-1601409808",
            "ProductRelationship": "SOL",
            "iTradeAccountKey": "-1537503308"
        }, {
            "dateOpened": "2015-06-03-04:00",
            "productCode": "SAV",
            "balance_amt": "0.00",
            "ProductSubCode": "MS",
            "accountName": "Momentum Savings",
            "classifications": [{
                "REL_ACTIVITY": "HighInterestBonus",
                "detail": "HighInterestBonus",
                "default": "Savings",
                "RETAIL_BANKING": "Saving"
            }],
            "currency": "CAD",
            "ddAccountNum": "405920426385",
            "category": "Banking",
            "STEPIndent": false,
            "balance": "0.00",
            "AccountKind": "FZN",
            "segCategory": "Banking",
            "entitlements": "dddd,adet,view,hpas,crin,svst,ahis",
            "branchLocatorTransit": "40592",
            "id": "************6385",
            "BankAcctStatusCode": "OP",
            "accountKey": "-1570963375",
            "ProductRelationship": "SOL",
            "iTradeAccountKey": "-1507056875"
        }, {
            "dateOpened": "2015-03-07-05:00",
            "productCode": "SAV",
            "balance_amt": "26246.76",
            "ProductSubCode": "MS",
            "accountName": "Momentum Savings",
            "classifications": [{
                "REL_ACTIVITY": "HighInterestBonus",
                "detail": "HighInterestBonus",
                "default": "Savings",
                "RETAIL_BANKING": "Saving"
            }],
            "currency": "CAD",
            "ddAccountNum": "405922206021",
            "category": "Banking",
            "STEPIndent": false,
            "balance": "26,246.76",
            "AccountKind": "ACT",
            "segCategory": "Banking",
            "entitlements": "tret,ipfr,adet,dddd,wsen,emtr,tto,tfro,ttfv,mpfs,mpfr,dcto,tref,view,ttfu,ipdi,crin,hpas,svst,bfro,ldac,ahis",
            "branchLocatorTransit": "40592",
            "id": "************6021",
            "BankAcctStatusCode": "OP",
            "accountKey": "82296368",
            "ProductRelationship": "SOL",
            "iTradeAccountKey": "146202868"
        }, {
            "dateOpened": "2015-03-07-05:00",
            "productCode": "SAV",
            "balance_amt": "27292.12",
            "ProductSubCode": "MS",
            "accountName": "Momentum Savings",
            "classifications": [{
                "REL_ACTIVITY": "HighInterestBonus",
                "detail": "HighInterestBonus",
                "default": "Savings",
                "RETAIL_BANKING": "Saving"
            }],
            "currency": "CAD",
            "ddAccountNum": "405922284227",
            "category": "Banking",
            "STEPIndent": false,
            "balance": "27,292.12",
            "AccountKind": "ACT",
            "segCategory": "Banking",
            "entitlements": "tret,ipfr,adet,dddd,wsen,emtr,tto,tfro,ttfv,mpfs,mpfr,dcto,tref,view,ttfu,ipdi,crin,hpas,svst,bfro,ldac,ahis",
            "branchLocatorTransit": "40592",
            "id": "************4227",
            "BankAcctStatusCode": "OP",
            "accountKey": "309542302",
            "ProductRelationship": "SOL",
            "iTradeAccountKey": "373448802"
        }, {
            "id": "************2123",
            "category": "Banking",
            "classifications": [{
                "REL_ACTIVITY": "RetailDep",
                "detail": "Deposit",
                "default": "Savings",
                "RETAIL_BANKING": "Chequing"
            }],
            "BankAcctStatusCode": "OP",
            "ProductRelationship": "ORP",
            "segCategory": "Banking",
            "ProductSubCode": "PC",
            "balance": "9,998,332.85",
            "productCode": "SAV",
            "AccountKind": "ACT",
            "entitlements": "tret,adet,dddd,wsen,emtr,tto,tfro,ttfv,mpfs,mpfr,dcto,crel,view,ttfu,hpas,svst,bfro,ldac,ahis",
            "accountName": "Powerchequing",
            "balance_amt": "9998332.85",
            "STEPIndent": false,
            "accountKey": "-801141069",
            "ddAccountNum": "405920032123",
            "currency": "CAD",
            "iTradeAccountKey": "-737234569"
        }, {
            "id": "************4929",
            "category": "Banking",
            "classifications": [{
                "REL_ACTIVITY": "RetailDep",
                "detail": "Deposit",
                "default": "Savings",
                "RETAIL_BANKING": "Chequing"
            }],
            "BankAcctStatusCode": "OP",
            "ProductRelationship": "ORP",
            "segCategory": "Banking",
            "ProductSubCode": "PC",
            "balance": "189,344.95",
            "productCode": "SAV",
            "AccountKind": "ACT",
            "entitlements": "tret,adet,dddd,wsen,emtr,tto,tfro,ttfv,mpfs,mpfr,dcto,crel,view,ttfu,hpas,svst,bfro,ldac,ahis",
            "accountName": "Powerchequing",
            "balance_amt": "189344.95",
            "STEPIndent": false,
            "accountKey": "-468288912",
            "ddAccountNum": "800020464929",
            "currency": "CAD",
            "iTradeAccountKey": "-404382412"
        }, {
            "dateOpened": "2008-01-04-05:00",
            "productCode": "SAV",
            "balance_amt": "-3981.21",
            "ProductSubCode": "SO",
            "accountName": "Scotia One",
            "classifications": [{
                "REL_ACTIVITY": "RetailDep",
                "detail": "Deposit",
                "default": "Savings",
                "RETAIL_BANKING": "Chequing"
            }],
            "currency": "CAD",
            "ddAccountNum": "018000014923",
            "category": "Banking",
            "STEPIndent": false,
            "balance": "-3,981.21",
            "AccountKind": "FZN",
            "segCategory": "Banking",
            "entitlements": "crco,dddd,adet,view,hpas,svst,vonl,ahis",
            "branchLocatorTransit": "01800",
            "id": "************4923",
            "BankAcctStatusCode": "OP",
            "accountKey": "439057245",
            "ProductRelationship": "SOL",
            "iTradeAccountKey": "502963745"
        }, {
            "dateOpened": "2007-02-19-05:00",
            "productCode": "SAV",
            "balance_amt": "-872251.81",
            "ProductSubCode": "SO",
            "accountName": "Scotia One",
            "classifications": [{
                "REL_ACTIVITY": "RetailDep",
                "detail": "Deposit",
                "default": "Savings",
                "RETAIL_BANKING": "Chequing"
            }],
            "currency": "CAD",
            "ddAccountNum": "800020156582",
            "category": "Banking",
            "STEPIndent": false,
            "balance": "-872,251.81",
            "AccountKind": "FZN",
            "segCategory": "Banking",
            "entitlements": "crco,dddd,adet,view,hpas,svst,vonl,ahis",
            "branchLocatorTransit": "80002",
            "id": "************6582",
            "BankAcctStatusCode": "OP",
            "accountKey": "1137271722",
            "ProductRelationship": "SOL",
            "iTradeAccountKey": "1201178222"
        }, {
            "dateOpened": "2015-04-30-04:00",
            "productCode": "SAV",
            "balance_amt": "0.00",
            "ProductSubCode": "HI",
            "accountName": "Scotia Power Savings",
            "classifications": [{
                "REL_ACTIVITY": "RetailHighInterest",
                "detail": "HighInterest",
                "default": "Savings",
                "RETAIL_BANKING": "Saving"
            }],
            "currency": "CAD",
            "ddAccountNum": "405922356422",
            "category": "Banking",
            "STEPIndent": false,
            "balance": "0.00",
            "AccountKind": "FZN",
            "segCategory": "Banking",
            "entitlements": "dddd,adet,view,hpas,crin,svst,ahis",
            "branchLocatorTransit": "40592",
            "id": "************6422",
            "BankAcctStatusCode": "OP",
            "accountKey": "1113064834",
            "ProductRelationship": "SOL",
            "iTradeAccountKey": "1176971334"
        }, {
            "dateOpened": "2015-06-03-04:00",
            "productCode": "SAV",
            "balance_amt": "0.00",
            "ProductSubCode": "HI",
            "accountName": "Scotia Power Savings",
            "classifications": [{
                "REL_ACTIVITY": "RetailHighInterest",
                "detail": "HighInterest",
                "default": "Savings",
                "RETAIL_BANKING": "Saving"
            }],
            "currency": "CAD",
            "ddAccountNum": "800020160288",
            "category": "Banking",
            "STEPIndent": false,
            "balance": "0.00",
            "AccountKind": "FZN",
            "segCategory": "Banking",
            "entitlements": "dddd,adet,view,hpas,crin,svst,ahis",
            "branchLocatorTransit": "80002",
            "id": "************0288",
            "BankAcctStatusCode": "OP",
            "accountKey": "1160270213",
            "ProductRelationship": "SOL",
            "iTradeAccountKey": "1224176713"
        }, {
            "dateOpened": "2011-09-09-04:00",
            "productCode": "SAV",
            "balance_amt": "868711.15",
            "ProductSubCode": "MA",
            "accountName": "Scotiabank Momentum Chequing",
            "classifications": [{
                "REL_ACTIVITY": "RetailDep",
                "detail": "DepositMoneyback",
                "default": "Savings",
                "RETAIL_BANKING": "Chequing"
            }],
            "currency": "CAD",
            "ddAccountNum": "800020464783",
            "category": "Banking",
            "STEPIndent": false,
            "balance": "868,711.15",
            "AccountKind": "ACT",
            "segCategory": "Banking",
            "entitlements": "tret,ipfr,adet,dddd,wsen,emtr,tto,tfro,ttfv,mpfs,mpfr,dcto,crel,tref,view,ttfu,ipdi,hpas,svst,bfro,ldac,ahis",
            "branchLocatorTransit": "80002",
            "id": "************4783",
            "BankAcctStatusCode": "OP",
            "accountKey": "-468343009",
            "ProductRelationship": "SOL",
            "iTradeAccountKey": "-404436509"
        }, {
            "dateOpened": "2015-06-03-04:00",
            "productCode": "SAV",
            "balance_amt": "0.00",
            "ProductSubCode": "BM",
            "accountName": "Money Master",
            "classifications": [{
                "REL_ACTIVITY": "RetailMoneyMaster",
                "detail": "MoneyMaster",
                "default": "Savings",
                "RETAIL_BANKING": "Saving"
            }],
            "currency": "CAD",
            "ddAccountNum": "405920575984",
            "category": "Banking",
            "STEPIndent": false,
            "balance": "0.00",
            "AccountKind": "FZN",
            "segCategory": "Banking",
            "entitlements": "crco,dddd,adet,view,hpas,svst,ahis",
            "branchLocatorTransit": "40592",
            "id": "************5984",
            "BankAcctStatusCode": "OP",
            "accountKey": "-541059092",
            "ProductRelationship": "SOL",
            "iTradeAccountKey": "-477152592"
        }, {
            "dateOpened": "2015-04-07-04:00",
            "productCode": "SAV",
            "balance_amt": "167.43",
            "ProductSubCode": "BM",
            "accountName": "Money Master",
            "classifications": [{
                "REL_ACTIVITY": "RetailMoneyMaster",
                "detail": "MoneyMaster",
                "default": "Savings",
                "RETAIL_BANKING": "Saving"
            }],
            "currency": "CAD",
            "ddAccountNum": "800020886483",
            "category": "Banking",
            "STEPIndent": false,
            "balance": "167.43",
            "AccountKind": "FZN",
            "segCategory": "Banking",
            "entitlements": "crco,dddd,adet,view,hpas,svst,ahis",
            "branchLocatorTransit": "80002",
            "id": "************6483",
            "BankAcctStatusCode": "OP",
            "accountKey": "-1154279939",
            "ProductRelationship": "SOL",
            "iTradeAccountKey": "-1090373439"
        }, {
            "iTradeAccountKey": "-666283035",
            "productCode": "VCL",
            "balance_amt": "-48620.21",
            "ProductSubCode": "ZZ",
            "accountName": "SCENE VISA card",
            "classifications": [{
                "REL_ACTIVITY": "VisaScene",
                "detail": "VisaScene",
                "default": "Visa",
                "RETAIL_BANKING": " "
            }],
            "currency": "CAD",
            "creditorInsuranceIndicator": "V",
            "ddAccountNum": "4537330026227020",
            "category": "Borrowing",
            "STEPIndent": false,
            "balance": "-48,620.21",
            "AccountKind": "ACT",
            "segCategory": "Borrowing",
            "entitlements": "tret,ipfr,itfc,adet,tfro,tto,ttfv,mpfr,crce,hpli,view,bast,bfro,ahis,ascc",
            "branchLocatorTransit": "80002",
            "id": "************7020",
            "cardImageAlias": "credit_scenevisa",
            "BankAcctStatusCode": "OP",
            "accountKey": "-730189535",
            "ProductRelationship": "SOL",
            "dateOpened": "2011-09-01-04:00"
        }, {
            "iTradeAccountKey": "633018689",
            "productCode": "MOR",
            "balance_amt": "72067.70",
            "ProductSubCode": "UN",
            "accountName": "Scotia Mortgage",
            "classifications": [{
                "REL_ACTIVITY": "Mortgage",
                "detail": "Mortgage",
                "default": "Mortgage",
                "RETAIL_BANKING": " "
            }],
            "currency": "CAD",
            "creditorInsuranceIndicator": "N",
            "ddAccountNum": "1000804",
            "category": "Borrowing",
            "STEPIndent": false,
            "balance": "72,067.70",
            "AccountKind": "ACT",
            "segCategory": "Borrowing",
            "entitlements": "hpli,adet,view,mmai,msta",
            "branchLocatorTransit": "40592",
            "id": "************0804",
            "BankAcctStatusCode": "OP",
            "accountKey": "569112189",
            "ProductRelationship": "COS",
            "dateOpened": "2005-10-04-04:00"
        }, {
            "iTradeAccountKey": "1991754897",
            "productCode": "VIC",
            "balance_amt": "-50016.22",
            "ProductSubCode": "RG",
            "accountName": "ScotiaLine Line of Credit",
            "classifications": [{
                "REL_ACTIVITY": "RetailVisa",
                "detail": "Visa",
                "default": "Visa",
                "RETAIL_BANKING": " "
            }],
            "currency": "CAD",
            "creditorInsuranceIndicator": "V",
            "ddAccountNum": "4538110024960015",
            "category": "Borrowing",
            "STEPIndent": false,
            "balance": "-50,016.22",
            "AccountKind": "ACT",
            "segCategory": "Borrowing",
            "entitlements": "hpli,adet,view,bast,vonl,ascc,ahis,crce",
            "branchLocatorTransit": "80002",
            "id": "************0015",
            "cardImageAlias": "credit_scotialinevisa",
            "BankAcctStatusCode": "OP",
            "accountKey": "1927848112",
            "ProductRelationship": "SOL",
            "dateOpened": "2011-09-01-04:00"
        }, {
            "iTradeAccountKey": "-1266248732",
            "productCode": "VLR",
            "balance_amt": "-94333.72",
            "ProductSubCode": "RC",
            "accountName": "Scotiabank Rewards VISA Card",
            "classifications": [{
                "REL_ACTIVITY": "VisaRewards",
                "detail": "VisaRewards",
                "default": "Visa",
                "RETAIL_BANKING": " "
            }],
            "currency": "CAD",
            "creditorInsuranceIndicator": "Y",
            "ddAccountNum": "4537360037110105",
            "category": "Borrowing",
            "STEPIndent": false,
            "balance": "-94,333.72",
            "AccountKind": "ACT",
            "segCategory": "Borrowing",
            "entitlements": "tret,ipfr,itfc,adet,tfro,tto,ttfv,mpfr,crce,hpli,view,bast,bfro,ahis,ascc",
            "branchLocatorTransit": "01800",
            "id": "************0105",
            "cardImageAlias": "credit_scotiarewards",
            "BankAcctStatusCode": "OP",
            "accountKey": "-1330155232",
            "ProductRelationship": "COS",
            "dateOpened": "2012-07-01-04:00"
        }, {
            "productCode": "NRS",
            "usd_balance": "7,042.23",
            "ProductSubCode": "",
            "cad_balance": "14,720.77",
            "accountName": "Non-Reg Savings - BNS",
            "classifications": [{
                "REL_ACTIVITY": "RetailNonRegBNS",
                "detail": "IP",
                "default": "BNS",
                "RETAIL_BANKING": " "
            }],
            "usd_balance_amt": "7042.23",
            "ddAccountNum": "000000001189364",
            "category": "Investing",
            "STEPIndent": false,
            "AccountKind": "ACT",
            "branchLocatorTransit": "40592",
            "segCategory": "Investing",
            "cad_balance_amt": "14720.77",
            "entitlements": "adet,view,nbw,iepu,hpas,hinv,srin,isoc,ibp",
            "id": "************9364",
            "BankAcctStatusCode": "OP",
            "accountKey": "-1838897071",
            "ProductRelationship": "SOL",
            "iTradeAccountKey": "-1774990571"
        }, {
            "productCode": "NRS",
            "usd_balance": "0.00",
            "ProductSubCode": "",
            "cad_balance": "101.51",
            "accountName": "Non-Reg Savings - BNS",
            "classifications": [{
                "REL_ACTIVITY": "RetailNonRegBNS",
                "detail": "IP",
                "default": "BNS",
                "RETAIL_BANKING": " "
            }],
            "usd_balance_amt": "0",
            "ddAccountNum": "000000001324631",
            "category": "Investing",
            "STEPIndent": false,
            "AccountKind": "ACT",
            "branchLocatorTransit": "40592",
            "segCategory": "Investing",
            "cad_balance_amt": "101.51",
            "entitlements": "adet,view,nbw,iepu,hpas,hinv,srin,isoc,ibp",
            "id": "************4631",
            "BankAcctStatusCode": "OP",
            "accountKey": "-240195823",
            "ProductRelationship": "SOL",
            "iTradeAccountKey": "-176289323"
        }, {
            "productCode": "NRS",
            "usd_balance": "0.00",
            "ProductSubCode": "",
            "cad_balance": "0.00",
            "accountName": "Non-Reg Savings - BNS",
            "classifications": [{
                "REL_ACTIVITY": "RetailNonRegBNS",
                "detail": "IP",
                "default": "BNS",
                "RETAIL_BANKING": " "
            }],
            "usd_balance_amt": "0",
            "ddAccountNum": "000000001511146",
            "category": "Investing",
            "STEPIndent": false,
            "AccountKind": "ACT",
            "branchLocatorTransit": "40592",
            "segCategory": "Investing",
            "cad_balance_amt": "0",
            "entitlements": "adet,view,nbw,iepu,hpas,hinv,srin,isoc,ibp",
            "id": "************1146",
            "BankAcctStatusCode": "OP",
            "accountKey": "1503263986",
            "ProductRelationship": "SOL",
            "iTradeAccountKey": "1567170486"
        }, {
            "productCode": "NRS",
            "usd_balance": "1,006.14",
            "ProductSubCode": "",
            "cad_balance": "3,012.88",
            "accountName": "Non-Reg Savings - BNS",
            "classifications": [{
                "REL_ACTIVITY": "RetailNonRegBNS",
                "detail": "IP",
                "default": "BNS",
                "RETAIL_BANKING": " "
            }],
            "usd_balance_amt": "1006.14",
            "ddAccountNum": "000000001511161",
            "category": "Investing",
            "STEPIndent": false,
            "AccountKind": "ACT",
            "branchLocatorTransit": "40592",
            "segCategory": "Investing",
            "cad_balance_amt": "3012.88",
            "entitlements": "adet,view,nbw,iepu,hpas,hinv,srin,isoc,ibp",
            "id": "************1161",
            "BankAcctStatusCode": "OP",
            "accountKey": "1503265753",
            "ProductRelationship": "SOL",
            "iTradeAccountKey": "1567172253"
        }, {
            "productCode": "NRS",
            "usd_balance": "0.00",
            "ProductSubCode": "",
            "cad_balance": "0.00",
            "accountName": "Non-Reg Savings - BNS",
            "classifications": [{
                "REL_ACTIVITY": "RetailNonRegBNS",
                "detail": "IP",
                "default": "BNS",
                "RETAIL_BANKING": " "
            }],
            "usd_balance_amt": "0",
            "ddAccountNum": "000000001511286",
            "category": "Investing",
            "STEPIndent": false,
            "AccountKind": "ACT",
            "branchLocatorTransit": "40592",
            "segCategory": "Investing",
            "cad_balance_amt": "0",
            "entitlements": "adet,view,nbw,hpas,hinv,srin,isoc,ibp",
            "id": "************1286",
            "BankAcctStatusCode": "OP",
            "accountKey": "1503297621",
            "ProductRelationship": "OTH",
            "iTradeAccountKey": "1567204121"
        }, {
            "productCode": "NRS",
            "usd_balance": "0.00",
            "ProductSubCode": "PR",
            "cad_balance": "979,547.74",
            "accountName": "Non-Reg Savings - SSI",
            "classifications": [{
                "REL_ACTIVITY": "RetailNonRegSSI",
                "detail": "IP",
                "default": "SSI",
                "RETAIL_BANKING": " "
            }],
            "usd_balance_amt": "0",
            "ddAccountNum": "000000000181412",
            "category": "Investing",
            "STEPIndent": false,
            "AccountKind": "ACT",
            "branchLocatorTransit": "71506",
            "segCategory": "Investing",
            "cad_balance_amt": "979547.74",
            "entitlements": "isp,adet,view,iepu,hpas,nsw,hinv,srin,isoc,mfsw",
            "id": "************1412",
            "BankAcctStatusCode": "OP",
            "accountKey": "705896646",
            "ProductRelationship": "SOL",
            "iTradeAccountKey": "769805708"
        }, {
            "productCode": "RRI",
            "usd_balance": "0.00",
            "ProductSubCode": "SB",
            "cad_balance": "219,157.24",
            "accountName": "Registered Income - BNS",
            "classifications": [{
                "REL_ACTIVITY": "none",
                "detail": "IP",
                "default": "BNS",
                "RETAIL_BANKING": " "
            }],
            "usd_balance_amt": "0",
            "ddAccountNum": "000000001265354",
            "category": "Investing",
            "STEPIndent": false,
            "AccountKind": "ACT",
            "branchLocatorTransit": "80002",
            "segCategory": "Investing",
            "cad_balance_amt": "219157.24",
            "entitlements": "adet,view,hpas,hinv,srin,isoc",
            "id": "************5354",
            "BankAcctStatusCode": "OP",
            "accountKey": "-1012346737",
            "ProductRelationship": "SOL",
            "iTradeAccountKey": "-948437598"
        }, {
            "productCode": "RRI",
            "usd_balance": "0.00",
            "ProductSubCode": "",
            "cad_balance": "2,002.32",
            "accountName": "Registered Income - SSI",
            "classifications": [{
                "REL_ACTIVITY": "none",
                "detail": "IP",
                "default": "SSI",
                "RETAIL_BANKING": " "
            }],
            "usd_balance_amt": "0",
            "ddAccountNum": "000000001264936",
            "category": "Investing",
            "STEPIndent": false,
            "AccountKind": "ACT",
            "branchLocatorTransit": "80002",
            "segCategory": "Investing",
            "cad_balance_amt": "2002.32",
            "entitlements": "adet,view,hpas,hinv,srin,isoc",
            "id": "************4936",
            "BankAcctStatusCode": "OP",
            "accountKey": "-1013093372",
            "ProductRelationship": "SOL",
            "iTradeAccountKey": "-949186872"
        }, {
            "productCode": "RRI",
            "usd_balance": "0.00",
            "ProductSubCode": "",
            "cad_balance": "2,002.32",
            "accountName": "Registered Income - SSI",
            "classifications": [{
                "REL_ACTIVITY": "none",
                "detail": "IP",
                "default": "SSI",
                "RETAIL_BANKING": " "
            }],
            "usd_balance_amt": "0",
            "ddAccountNum": "000000001264944",
            "category": "Investing",
            "STEPIndent": false,
            "AccountKind": "ACT",
            "branchLocatorTransit": "80002",
            "segCategory": "Investing",
            "cad_balance_amt": "2002.32",
            "entitlements": "adet,view,hpas,hinv,srin,isoc",
            "id": "************4944",
            "BankAcctStatusCode": "OP",
            "accountKey": "-1013092473",
            "ProductRelationship": "SOL",
            "iTradeAccountKey": "-949185973"
        }, {
            "productCode": "TFS",
            "usd_balance": "0.00",
            "ProductSubCode": "SB",
            "cad_balance": "3,184.61",
            "accountName": "Tax-Free Savings - BNS",
            "classifications": [{
                "REL_ACTIVITY": "TFSABNS",
                "detail": "IP",
                "default": "BNS",
                "RETAIL_BANKING": " "
            }],
            "usd_balance_amt": "0",
            "ddAccountNum": "000000000406956",
            "category": "Investing",
            "STEPIndent": false,
            "AccountKind": "ACT",
            "branchLocatorTransit": "80002",
            "segCategory": "Investing",
            "cad_balance_amt": "3184.61",
            "entitlements": "adet,view,iepu,hpas,hinv,srin,isoc,twfr,ibp",
            "id": "************6956",
            "BankAcctStatusCode": "OP",
            "accountKey": "-1150822287",
            "ProductRelationship": "SOL",
            "iTradeAccountKey": "-1086913148"
        }, {
            "productCode": "TFS",
            "usd_balance": "0.00",
            "ProductSubCode": "SB",
            "cad_balance": "102.48",
            "accountName": "Tax-Free Savings - BNS",
            "classifications": [{
                "REL_ACTIVITY": "TFSABNS",
                "detail": "IP",
                "default": "BNS",
                "RETAIL_BANKING": " "
            }],
            "usd_balance_amt": "0",
            "ddAccountNum": "000000000425631",
            "category": "Investing",
            "STEPIndent": false,
            "AccountKind": "ACT",
            "branchLocatorTransit": "80002",
            "segCategory": "Investing",
            "cad_balance_amt": "102.48",
            "entitlements": "adet,view,iepu,hpas,hinv,srin,isoc,twfr,ibp",
            "id": "************5631",
            "BankAcctStatusCode": "OP",
            "accountKey": "-1094578956",
            "ProductRelationship": "SOL",
            "iTradeAccountKey": "-1030669817"
        }, {
            "productCode": "TFS",
            "usd_balance": "0.00",
            "ProductSubCode": "",
            "cad_balance": "65,686.48",
            "accountName": "Tax-Free Savings - SSI",
            "classifications": [{
                "REL_ACTIVITY": "TFSASSI",
                "detail": "IP",
                "default": "SSI",
                "RETAIL_BANKING": " "
            }],
            "usd_balance_amt": "0",
            "ddAccountNum": "000000000425640",
            "category": "Investing",
            "STEPIndent": false,
            "AccountKind": "ACT",
            "branchLocatorTransit": "80002",
            "segCategory": "Investing",
            "cad_balance_amt": "65686.48",
            "entitlements": "isp,adet,view,iepu,hpas,hinv,srin,isoc,twfr,mfsw",
            "id": "************5640",
            "BankAcctStatusCode": "OP",
            "accountKey": "-1094578026",
            "ProductRelationship": "SOL",
            "iTradeAccountKey": "-1030671526"
        }, {
            "productCode": "TFS",
            "usd_balance": "0.00",
            "ProductSubCode": "",
            "cad_balance": "2,119.59",
            "accountName": "Tax-Free Savings - SSI",
            "classifications": [{
                "REL_ACTIVITY": "TFSASSI",
                "detail": "IP",
                "default": "SSI",
                "RETAIL_BANKING": " "
            }],
            "usd_balance_amt": "0",
            "ddAccountNum": "000000000425659",
            "category": "Investing",
            "STEPIndent": false,
            "AccountKind": "ACT",
            "branchLocatorTransit": "80002",
            "segCategory": "Investing",
            "cad_balance_amt": "2119.59",
            "entitlements": "isp,adet,view,iepu,hpas,hinv,srin,isoc,twfr,mfsw",
            "id": "************5659",
            "BankAcctStatusCode": "OP",
            "accountKey": "-1094576786",
            "ProductRelationship": "SOL",
            "iTradeAccountKey": "-1030670286"
        }, {
            "classifications": [{
                "REL_ACTIVITY": "SMDIBrk",
                "detail": "SDBI",
                "default": "Brokerage",
                "RETAIL_BANKING": ""
            }],
            "category": "BRK",
            "id": "************0961",
            "BankAcctStatusCode": "OP",
            "iTradeAccountKey": "542243514",
            "segCategory": "Investing",
            "cad_balance": "195,367.36",
            "ProductSubCode": "2",
            "productCode": "SL",
            "AccountKind": "Regular",
            "cad_balance_amt": "195367.36",
            "entitlements": "view",
            "usd_balance_amt": "14420.76",
            "accountName": "Scotia iTRADE - Margin",
            "STEPIndent": false,
            "accountKey": "478339605",
            "usd_balance": "14,420.76",
            "ddAccountNum": "55810961",
            "ProductRelationship": "SOL"
        }],
        "stuffIndicator": false,
        "entlLimits": [{
            "limitAmt": "0",
            "limitType": "dailyEntlLimit"
        }, {
            "limitAmt": "0",
            "limitType": "dailyAvailEntlLimit"
        }, {
            "limitAmt": "0",
            "limitType": "weeklyEntlLimit"
        }, {
            "limitAmt": "0",
            "limitType": "weeklyAvailEntlLimit"
        }],
        "containSIN": true,
        "staffIndicator": "N",
        "Status": [{
            "type": "0"
        }],
        "traceSession": "OYo5xFkNg5qWp-d9ff-94N7",
        "userSavedApplicationFlag": false,
        "opstatus": 0,
        "fullName": "MR DALLAS MAVERICKS",
        "fullNameTie": "1",
        "scotiaAdvisor": [],
        "httpStatusCode": 200,
        "entlMappings": [],
        "transactionId": "bd4fdd88-1200-4d94-8ad7-e568d93189b1",
        "cardType": "R",
        "CustomerEmail": "in@test.com",
        "custTrackId": "9574b752-c187-4696-a7cb-a1518d3fc872",
        "plasticCardInfo": [{
            "plasticCardSubType": "  ",
            "plasticCardType": " "
        }],
        "customer": [{
            "entlValue": "01",
            "entlId": "ITRADE_SEGMENT"
        }, {
            "entlValue": "0",
            "entlId": "ICLUB_ID"
        }, {
            "entlValue": "49999.99",
            "entlId": "BILL_PAYMENT_MAX_LIMIT"
        }, {
            "entlValue": "0.01",
            "entlId": "BILL_PAYMENT_MIN_LIMIT"
        }, {
            "entlValue": "49999.99",
            "entlId": "BUSINESS_LOAN_PREPAYMENT_MAX_LIMIT"
        }, {
            "entlValue": "0.01",
            "entlId": "BUSINESS_LOAN_PREPAYMENT_MIN_LIMIT"
        }, {
            "entlValue": "3000.0",
            "entlId": "EMT_MAX_LIMIT"
        }, {
            "entlValue": "10.0",
            "entlId": "EMT_MIN_LIMIT"
        }, {
            "entlValue": "5000",
            "entlId": "GIC_PURCHASE_MAX_LIMIT"
        }, {
            "entlValue": "1000",
            "entlId": "GIC_PURCHASE_MIN_LIMIT"
        }, {
            "entlValue": "49999.99",
            "entlId": "MORTGAGE_PREPAYMENT_MAX_LIMIT"
        }, {
            "entlValue": "0.01",
            "entlId": "MORTGAGE_PREPAYMENT_MIN_LIMIT"
        }, {
            "entlValue": "49999.99",
            "entlId": "RETAIL_LOAN_PREPAYMENT_MAX_LIMIT"
        }, {
            "entlValue": "0.01",
            "entlId": "RETAIL_LOAN_PREPAYMENT_MIN_LIMIT"
        }, {
            "entlValue": "3000.0",
            "entlId": "SCOTIA_TO_SCOTIA_MAX_LIMIT"
        }, {
            "entlValue": "1.0",
            "entlId": "SCOTIA_TO_SCOTIA_MIN_LIMIT"
        }, {
            "entlValue": "100000.0",
            "entlId": "TRANSFER_MAX_LIMIT"
        }, {
            "entlValue": "0.01",
            "entlId": "TRANSFER_MIN_LIMIT"
        }, {
            "entlValue": "49999.99",
            "entlId": "TRANSFER_RECURRING_MAX_LIMIT"
        }, {
            "entlValue": "0.01",
            "entlId": "TRANSFER_RECURRING_MIN_LIMIT"
        }, {
            "entlValue": "999.99",
            "entlId": "WU_MAX_LIMIT"
        }, {
            "entlValue": "1.0",
            "entlId": "WU_MIN_LIMIT"
        }],
        "SIN": "263119570",
        "scotiaKey": "5dde39da4735c4e7a06f04d7d669d0f46824190f750ed59744ca74b407067c94",
        "clientId": "9574b752-c187-4696-a7cb-a1518d3fc872",
        "httpresponse": {
            "url": "https://zeus.mobilebanking.scotiabank.com/mbanking/MWServlet",
            "responsecode": 200,
            "headers": {
                "Pragma": "no-cache",
                "Connection": "Keep-Alive",
                "Cache-Control": "no-store, no-cache, must-revalidate",
                "Content-Language": "en",
                "Content-Type": "text/plain;charset=UTF-8",
                "Date": "Wed, 16 Aug 2017 18:50:31 GMT",
                "Content-Length": "39755",
                "Keep-Alive": "timeout=5, max=98"
            }
        },
        "customerEntls": "1000,1001,1002,1004,1005,1006,1007,1008,1009,1011,1012,1013,1014,1015,1016,1023,1025,500,502,509,511,513,515,516,518,519,520,522,524,525,527,530,531,545,546,547,548,549,550,552,553,554,555,556,557,558,559,560,563,564,565,570,571,572,573,575,577,579,580,581,583,584,585,587,588,589,590,591,592,598,599,null",
        "permanentSIN": true,
        "traceTimestamp": "2017-08-16T14:50:32.0000570Z"
    },

];